name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      release:
        description: Create release
        required: false
        type: boolean
      version:
        description: New version to release
        required: false
        type: string

concurrency:
  group: ci/cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Swift Package
    runs-on: macos-12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup repository
      uses: SwiftyLab/ci/actions/setup@main

    - name: Run generate
      run: npm run generate
